index:
    path: /
    controller: App\Controller\ProviderController::index

newProvider:
    path: /newProvider
    controller: App\Controller\ProviderController::addProvider

editProvider:
    path: /editprovider/{id}
    controller: App\Controller\ProviderController::editProvider